DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Comment;

CREATE TABLE Author(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX author_name ON Author (name);

CREATE TABLE Genre(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX genre_name ON Genre (name);

CREATE TABLE Book (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  author_id BIGINT NOT NULL,
  genre_id BIGINT NOT NULL,
  CONSTRAINT name_author_genre UNIQUE (name, author_id, genre_id),
  FOREIGN KEY(author_id) REFERENCES Author(id) ON DELETE CASCADE,
  FOREIGN KEY(genre_id) REFERENCES Genre(id) ON DELETE CASCADE
);

CREATE TABLE Comment(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  content VARCHAR(255) NOT NULL,
  book_id BIGINT NOT NULL,
  FOREIGN KEY (book_id) REFERENCES Book(id) ON DELETE CASCADE
);